Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  #
  # Run Ansible from the Vagrant Host
  #
  if Vagrant::Util::Platform.windows? then
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.install_mode = "pip"
    end
  else
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
