Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
