---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos/7
  - name: ubuntu/bionic64

suites:
  - name: mongo
    includes:
      - centos/7
    run_list:
      - recipe[sc-mongodb::default]
    driver:
      network:
        - ["private_network", {ip: "192.168.50.3"}]
    attributes:
      mongodb:
        config:
          mongod:
            net:
              bindIp: 0.0.0.0
  - name: website
    includes:
      - ubuntu/bionic64
    run_list:
      - recipe[website::default]
    driver:
      network:
        - ["private_network", {ip: "192.168.50.2"}]
        - ["forwarded_port", {guest: 3000, host: 3000}]
    attributes: