# -*- mode: ruby -*-
# vi: set ft=ruby :
PROVISION = false
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  if PROVISION
    config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
    SHELL
  end
end
