# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative '../../lib/vagrant_helpers'

Vagrant.configure("2") do |config|
  # This will randomly pick either the ubuntu or centos box
  # config.vm.box = ["ubuntu/bionic64", "centos/7"].sample
  config.vm.box = ["ubuntu/bionic64"].sample
  # Allows you to talk to the Guest VM via port 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # You can also create methods or classes in a Vagrantfile
  configure_proxy(config)

  # Change the provisioner based on the selected box type
  if config.vm.box.include? 'centos'
    config.vm.provision "shell", inline: <<-SHELL
     yum update
     yum install -y httpd
    SHELL
  else
    config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
    SHELL
  end

  # Finally replace the default page with the local page instead
  config.vm.provision "file", source: "./files/index.html", destination: "index.html"
  # Won't have permission to move files by default
  config.vm.provision "shell", inline: <<-SHELL
   mv index.html /var/www/html
   service apache2 restart
  SHELL
end
