---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  become: true
  tasks:
  - name: ensure apache is at the latest version
    package: name=apache2 state=latest
  - name: write the new web page
    template: src=./template/index.html.j2 dest=/var/www/index.html
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
