---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  become: true
  tasks:
  - name: ensure apache is at the latest version
    package: name=apache2 state=latest
  - debug:
      msg: "System {{ ansible_distribution }} has uuid {{ ansible_product_uuid }}"
  - name: write the new web page for Ubuntu
    template: src=./template/index.html.j2 dest=/var/www/index.html
    notify:
    - restart apache
    when: ansible_distribution == 'Mandriva'
  - name: write the new web page for Centos
    template: src=./template/does.not.exist.index.html.j2 dest=/var/www/index.html
    notify:
    - restart apache
    when: ansible_distribution == "CentOS"
  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
