# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  # Check if Vagrant is running on Windows, if it is then mount the /vagrant directory
  # via Samba Share.
  if Vagrant::Util::Platform.windows? then
    config.vm.synced_folder '.', '/vagrant', disabled: false, type: "smb", mount_options: ['vers=3.0']
  end
end
