# -*- mode: ruby -*-
# vi: set ft=ruby :
# You can include any normal Ruby Script in a Vagrantfile, allowing for common functionality to be shared
# between multiple vagrant files.
require_relative '../../lib/vagrant_helpers'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  # Allows you to talk to the Guest VM via port 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080  
  configure_proxy(config)

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
   apt-get update
   apt-get install -y apache2
  SHELL

end
